### ISSUE TITLE
No matching samples found in CNA and expression data!?

### ISSUE THREAD

**Issue by Tman3** [jowkar/focalscan#2]
To whom it may concern:
I tried to perform FocalScan on a set of cancer data. I obtained the following error message, and would like to seek your view how I should troubleshoot the datasets used.  It appears to stem from the CNA data.
>>>>>>>>>>>>>>>>>>
Reading expression data
The first column of the csv-file contained only numbers. Assuming that rows (genes) correspond exactly to rows in the annotation file.
Finished reading expression data
Assuming 60498 gene/tile IDs and 494 samples
Performing percentile normalization
Reading copy number data
Mapping copy number data to gene/tile IDs
Warning: **More samples than genes provided. Check that samples correspond to columns and genes to rows in CNA data input.**
> In CNA (line 56)
  In FocalScan/read_data (line 397)
  In FocalScan (line 157)
Error using FocalScan/read_data (line 438)
**No matching samples found in the CNA and expression data**

Error in FocalScan (line 157)
>>>>>>>>>>>>>>>>>>>>
Those above numbers for gene IDs and samples of the expression files are correct.  I used a list of seg files to select the corresponding expression data to be used in the analysis. Therefore, there should be matching samples in the CNA and expression data. Both the gene IDs and annotation table are based on gencode v23.  Another dfference is that the file names used for expression data and the CNV segmented files in my study have 15 digits (vs. 12 digits in your example TCGA dataset,e.g., ABCD-xx-yyyy-zz).

Any inputs will be much appreciated!

**Comment by jowkar** [comment]
It seems that the expression data was read correctly (since the logged output printed "Assuming 60498 gene/tile IDs and 494 samples"), but that something goes wrong when reading the CNA data. The warning thrown before the error was meant to indicate when a CNA data CSV file is transposed the wrong way, that is, if samples were provided in rows instead of columns. If that was the case, the program would then fail to match the expression and CNA input data. This would be the first thing to double check. (Also check so that there is not a blank space before the first sample name in the header row, which may sometimes be encountered when exporting a CSV file from R.) 

Was the CNA data provided in CSV format or as one seg file containing data for all samples? If the CNA data was instead provided in the form of a seg file, it could possibly be that this file is formatted in an unexpected way or that it for some reason fails to match the annotation file (potentially, but unlikely, the error could also stem from the annotation file).

If the TCGA sample barcodes are 15 digits, double check so that the last one or two characters are not different between the expression and copy number datasets. Sometimes it could for instance be that the barcode ends with -01A in the expression dataset and -01B in the copy number data, which is easy to miss. I usually truncate the IDs to 12 digits before analysis for this reason. Other than that it should not be a problem having 15 instead of 12 digits.

These would be the most likely problems that I can think of, but I'll be happy to assist further if this does not solve the issue.

**Comment by Tman3** [comment]
Thanks!  I will review the above carefully with my datasets.
By the way, I just sent an e-mail to Professor Larsson seeking for help before I see your above reply.
That e-mail contained a bit more detailed.
Much appreciated!

**Comment by Tman3** [comment]
Following your comments above, I examined the CNA seg files and the annotation file closely and have the following observations:

To recap:
- Expression file is a CSV file with header row is the Sample ID and each row is associated with a gene id.
The gene id is sorted according to the order in the annotation BED file. The Sample ID in the header row is arranged from left to right in the same order of the samples in the CNA seg file.

- CNA seg file contained all the samples. For each CNA seg file, it is first sorted by Chr followed by Start pos. Then all expr associated CNA sample seg files are combined into a single one; same format as in the example.

- Annotation file is based on Gencode v23 at gene level. A subset of gene-id is selected based on the expression file data and is in BED format.  The file is sorted by gene id.  Gene symbols are not included.

My previous attempt used the gencode v23 BED file as the annotation file.   In the example presented in the paper, it used a gencode symbol files instead.

My questions are as follows:
If I use a CSV file for expression data and a Seg file for CNA data, could I use a Gencode file based on gene id?  This approach is slightly different from the example given, which used a gencode file based on gene symbols.

The Gencode17 BED file based on gene id was sorted by gene-id in the example.  On the other hand, the Gencode17_symbols BED file is ranked in a different order. (the first 3600+ gene symbols were arranged in their order of gene id; the remaining 52719 gene symbols are arranged in a different way).  Also the Gencode 17 BED file has 3,400+ more genes.

Kindly comment whether I have the correct format for the CNA files.  In addition, what is the criteria used to reduce the number of gene-id in the gene-symbol file? What are the factors to be considered? What should be the right order (or format) for the gene id BED file and for the gene symbol BED file.?

In the manual, it mentioned that seg file as CSV input to focalscan (pg 10).  What is the file format for such kind of CSV file? What is the parameter to be used in the command line?

On pg 13, there is a reference to a parameter "expr_seg"? I am unable to locate what is the purpose of such parameter, and how it should be used. 

Thank you for your attention!

**Comment by jowkar** [comment]
It sounds like you have the correct format of all files. I will try to see if I can find the problem, if you could send me the three input files or attach them here. Potentially it could be a bug. 

For the annotation BED file, the expected input should have four columns, where the last column specifies an ID for each gene. It should not matter whether this ID is a gene symbol or for instance an Ensembl ID, but the fourth column cannot be empty. If the expression data CSV file does not include any identifier for the genes, the annotation file should be sorted in the same order as the expression file. The program will then assign the identifiers in the annotation file to each corresponding row in the CSV file. If, however, there are identifiers in the expression data file, these will be automatically matched to the identifiers for each gene in the annotation file.

Regarding the difference in the number of entries in the annotation file with gene symbols compared to the with Ensembl IDs, this is because some genes had Emsembl IDs that did not translate to any gene symbol when I converted them to create the annotation file with gene symbols, so they were excluded.

In the manual, the reference to ”expr_seg” is a typo. It should be ”seg_file”. On page 10 and in my previous comment, I also referred to CNA input in the CSV format. You may disregard this, since this was something that was in fact only supported in a development version of the program but is not possible with the current release. Seg file input is the only option supported at the moment. I will correct these oversights in the documentation.

**Comment by Tman3** [comment]
Have sent you an e-mail to your university e-mail address with link to the files.
Many thanks!

**Comment by jowkar** [comment]
The issue was resolved. It was caused by a problem in the formatting of the seg file: columns were separated by three whitespace characters rather than a tab, and there were whitespaces after the last column in the file. This caused the program to fail reading the file properly.
